<h1>Welcome</h1>

<p>
  this is a demo of a sveltekit app with a login flow using email and time-based
  one-time password (TOTP) that are generated by apps like google authenticator,
  authy and many more
</p>
